### PR TITLE
avoid relying on garbage collection to close file

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by gotcha** [comment]
WIP

**Comment by sallner** [comment]
@gotcha Do you still want to work on this PR or can it be closed?

**Comment by gotcha** [comment]
Got out of my radar. Thanks for reminding me. I will check what is missing and decide.
--
Godefroid Chapelle

**Comment by icemac** [comment]
Any news on this PR, or should we close it?

**Comment by gotcha** [comment]
Seems time has passed... and I forgot what I was doing here.

**Pull request closed without merging**
